/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'xp' : bigint,
  'dex' : bigint,
  'int' : bigint,
  'str' : bigint,
  'vit' : bigint,
  'maxHP' : bigint,
  'status' : CharacterStatus,
  'currentHP' : bigint,
  'name' : string,
  'season' : bigint,
  'level' : bigint,
  'classTier' : bigint,
  'realm' : Realm,
}
export type CharacterCreationError = { 'noPermission' : null } |
  { 'alreadyExists' : null } |
  { 'limitReached' : null };
export type CharacterId = number;
export type CharacterStatus = { 'Dead' : null } |
  { 'Alive' : null };
export type ExternalBlob = Uint8Array;
export interface Item {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'stats' : {
    'dex' : bigint,
    'int' : bigint,
    'str' : bigint,
    'vit' : bigint,
    'bonus' : string,
  },
  'itemType' : ItemType,
  'rarity' : Rarity,
}
export type ItemType = { 'Weapon' : null } |
  { 'Armor' : null } |
  { 'Trinket' : null };
export interface MarketplaceListing {
  'active' : boolean,
  'item' : Item,
  'seller' : Principal,
  'price' : bigint,
}
export type Rarity = { 'Rare' : null } |
  { 'Uncommon' : null } |
  { 'Legendary' : null } |
  { 'Common' : null };
export type Realm = { 'Hardcore' : null } |
  { 'Softcore' : null };
export type SetHpError = { 'noPermission' : null } |
  { 'characterNotFound' : null } |
  { 'maxHPExceeded' : null } |
  { 'alreadyFullHP' : null };
export interface UserProfile { 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyItem' : ActorMethod<[string], undefined>,
  'createCharacter' : ActorMethod<
    [string, Realm],
    { 'ok' : CharacterId } |
      { 'err' : CharacterCreationError }
  >,
  'deleteCharacter' : ActorMethod<[CharacterId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacters' : ActorMethod<[], Array<Character>>,
  'getItem' : ActorMethod<[string], [] | [Item]>,
  'getItemImage' : ActorMethod<[string], ExternalBlob>,
  'getMarketplaceListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listItemForSale' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCharacterHp' : ActorMethod<
    [CharacterId, bigint],
    { 'ok' : null } |
      { 'err' : SetHpError }
  >,
  'uploadItemImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];