/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Realm = IDL.Variant({
  'Hardcore' : IDL.Null,
  'Softcore' : IDL.Null,
});
export const CharacterId = IDL.Nat8;
export const CharacterCreationError = IDL.Variant({
  'noPermission' : IDL.Null,
  'alreadyExists' : IDL.Null,
  'limitReached' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'username' : IDL.Text });
export const CharacterStatus = IDL.Variant({
  'Dead' : IDL.Null,
  'Alive' : IDL.Null,
});
export const Character = IDL.Record({
  'xp' : IDL.Nat,
  'dex' : IDL.Nat,
  'int' : IDL.Nat,
  'str' : IDL.Nat,
  'vit' : IDL.Nat,
  'maxHP' : IDL.Nat,
  'status' : CharacterStatus,
  'currentHP' : IDL.Nat,
  'name' : IDL.Text,
  'season' : IDL.Nat,
  'level' : IDL.Nat,
  'classTier' : IDL.Nat,
  'realm' : Realm,
});
export const ItemType = IDL.Variant({
  'Weapon' : IDL.Null,
  'Armor' : IDL.Null,
  'Trinket' : IDL.Null,
});
export const Rarity = IDL.Variant({
  'Rare' : IDL.Null,
  'Uncommon' : IDL.Null,
  'Legendary' : IDL.Null,
  'Common' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'stats' : IDL.Record({
    'dex' : IDL.Nat,
    'int' : IDL.Nat,
    'str' : IDL.Nat,
    'vit' : IDL.Nat,
    'bonus' : IDL.Text,
  }),
  'itemType' : ItemType,
  'rarity' : Rarity,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MarketplaceListing = IDL.Record({
  'active' : IDL.Bool,
  'item' : Item,
  'seller' : IDL.Principal,
  'price' : IDL.Nat,
});
export const SetHpError = IDL.Variant({
  'noPermission' : IDL.Null,
  'characterNotFound' : IDL.Null,
  'maxHPExceeded' : IDL.Null,
  'alreadyFullHP' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyItem' : IDL.Func([IDL.Text], [], []),
  'createCharacter' : IDL.Func(
      [IDL.Text, Realm],
      [IDL.Variant({ 'ok' : CharacterId, 'err' : CharacterCreationError })],
      [],
    ),
  'deleteCharacter' : IDL.Func([CharacterId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
  'getItemImage' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
  'getMarketplaceListings' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listItemForSale' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCharacterHp' : IDL.Func(
      [CharacterId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : SetHpError })],
      [],
    ),
  'uploadItemImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Realm = IDL.Variant({ 'Hardcore' : IDL.Null, 'Softcore' : IDL.Null });
  const CharacterId = IDL.Nat8;
  const CharacterCreationError = IDL.Variant({
    'noPermission' : IDL.Null,
    'alreadyExists' : IDL.Null,
    'limitReached' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text });
  const CharacterStatus = IDL.Variant({
    'Dead' : IDL.Null,
    'Alive' : IDL.Null,
  });
  const Character = IDL.Record({
    'xp' : IDL.Nat,
    'dex' : IDL.Nat,
    'int' : IDL.Nat,
    'str' : IDL.Nat,
    'vit' : IDL.Nat,
    'maxHP' : IDL.Nat,
    'status' : CharacterStatus,
    'currentHP' : IDL.Nat,
    'name' : IDL.Text,
    'season' : IDL.Nat,
    'level' : IDL.Nat,
    'classTier' : IDL.Nat,
    'realm' : Realm,
  });
  const ItemType = IDL.Variant({
    'Weapon' : IDL.Null,
    'Armor' : IDL.Null,
    'Trinket' : IDL.Null,
  });
  const Rarity = IDL.Variant({
    'Rare' : IDL.Null,
    'Uncommon' : IDL.Null,
    'Legendary' : IDL.Null,
    'Common' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'stats' : IDL.Record({
      'dex' : IDL.Nat,
      'int' : IDL.Nat,
      'str' : IDL.Nat,
      'vit' : IDL.Nat,
      'bonus' : IDL.Text,
    }),
    'itemType' : ItemType,
    'rarity' : Rarity,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MarketplaceListing = IDL.Record({
    'active' : IDL.Bool,
    'item' : Item,
    'seller' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const SetHpError = IDL.Variant({
    'noPermission' : IDL.Null,
    'characterNotFound' : IDL.Null,
    'maxHPExceeded' : IDL.Null,
    'alreadyFullHP' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyItem' : IDL.Func([IDL.Text], [], []),
    'createCharacter' : IDL.Func(
        [IDL.Text, Realm],
        [IDL.Variant({ 'ok' : CharacterId, 'err' : CharacterCreationError })],
        [],
      ),
    'deleteCharacter' : IDL.Func([CharacterId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
    'getItemImage' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
    'getMarketplaceListings' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listItemForSale' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCharacterHp' : IDL.Func(
        [CharacterId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : SetHpError })],
        [],
      ),
    'uploadItemImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };